ezyplot-x1/force-app/main/default/objects/Area_retrieval_status__c/Area_retrieval_status__c.object-meta.xml
<CustomObject>
    <label>Area_retrieval_status</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Area_retrieval_status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ezyplot-x1/force-app/main/default/objects/Area_retrieval_status__c/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <defaultValue>&#39;gu35 0gj&#39;</defaultValue>
    <label>Area</label>
    <length>99</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Area_retrieval_status__c/fields/LR_trans_data_retrieval_required__c.field-meta.xml
<CustomField>
    <fullName>LR_trans_data_retrieval_required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LR Trans data retrieval required</label>
    <type>Checkbox</type>
</CustomField>

ezyplot-x1/force-app/main/default/classes/enqueue_1.cls
public with sharing class enqueue_1 {
    public enqueue_1() {

        // *** >> **********************    S U P E R   I M P O R T A N T *****

        // Check for remaining Areas that need their LR Transactions retrieved *
        Area_Retrieval_Status__c[] LR_to_Queue = 
            [SELECT Id, Name, Area__c, LR_Trans_Data_retrieval_required__c
            FROM Area_Retrieval_Status__c 
            WHERE LR_Trans_Data_retrieval_required__c=TRUE 
            LIMIT 10];                                           // one is sufficient
        System.debug('Enqueue_1>> LR_Transactions to be queued: ' + LR_to_Queue);

        // IF there are Area that need LR retrieval..    
        if (LR_to_Queue.size() > 0){
            AsyncApexJob[] LR_in_Queue = [
                SELECT ApexClass.Name, Status
                FROM AsyncApexJob 
                WHERE apexClass.Name = 'enqueue_2'
                    AND (JobType='Queueable' AND Status IN ('Processing','Preparing','Queued')) 
                LIMIT 10] ;
            System.debug('Enqueue_1>> enqueue_2 IN queue: ' + LR_in_Queue);

            if (LR_in_Queue.size() == 0){
                System.debug('Enqueue_1>> Launching enqueue_2 ');
                ID jobId_2 = system.enqueuejob( new enqueue_2);            
            }
        }
        // *** << **********************    S U P E R   I M P O R T A N T *****


    }
}