ezyplot-x1/force-app/main/default/objects/Plot__c/Plot__c.object-meta.xml
<CustomObject>
    <label>Plot</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plots</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ezyplot-x1/force-app/main/default/objects/Plot__c/fields/Address_postcode__c.field-meta.xml
<CustomField>
    <fullName>Address_postcode__c</fullName>
    <label>Address_postcode</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Plot__c/fields/Address_town__c.field-meta.xml
<CustomField>
    <fullName>Address_town__c</fullName>
    <label>Address_town</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ezyplot-x1/force-app/main/default/classes/PlotSearchController.cls
public with sharing class PlotSearchController {
    @AuraEnabled
    public static List<Plot__c> searchPlots( String searchTerm ) {
        List<Plot__c> lstPlots = new List<Plot__c>();
        if ( String.isNotBlank( searchTerm ) 	&& searchTerm.length() > 1 ) {
            List<List<SObject>> searchResults = [
                FIND :searchTerm
                RETURNING Plot__c(
                    Id, Name, Address_town__c, Address_postcode__c
                    ORDER BY Name
                    LIMIT 10
                )
            ];
            lstPlots = searchResults[0];
        }
        return lstPlots;
    }
}