ezyplot-x1/force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <label>Offer</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Accepted__c.field-meta.xml
<CustomField>
    <fullName>Accepted__c</fullName>
    <formula>Offer_amount__c ==  Counter_offer__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Offer equals Counter offer</inlineHelpText>
    <label>Accepted</label>
    <type>Checkbox</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Counter_Date__c.field-meta.xml
<CustomField>
    <fullName>Counter_Date__c</fullName>
    <label>Counter Date</label>
    <type>Date</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Counter_offer__c.field-meta.xml
<CustomField>
    <fullName>Counter_offer__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Counter offer</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Offer_amount__c.field-meta.xml
<CustomField>
    <fullName>Offer_amount__c</fullName>
    <label>Offer amount</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Offer_Date__c.field-meta.xml
<CustomField>
    <fullName>Offer_Date__c</fullName>
    <label>Offer Date</label>
    <type>Date</type>
</CustomField>

ezyplot-x1/force-app/main/default/objects/Offer__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Offers</relationshipLabel>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

ezyplot-x1/force-app/main/default/classes/Offer_update.cls
/*
public with sharing class Offer_update {
    public Offer_update() {

    }
}
*/

public inherited sharing class Offer_update {

    /*         overview of all sections below:
    */    

        @InvocableMethod
        public static void Offer_update(List<Id> OfferIds)
        {
            List<Offer__c> Ids =
                [select id, Name, 
                    Accepted__c, Counter_date__c, Counter_offer__c, Offer_amount__c, Offer_date__c, 
                    Opportunity__c
                from Offer__c WHERE id in :OfferIds
                ];

            if (Ids.size()> 0){
                System.debug('Offer_update (Ids:) >> '+ Ids);

                // more efficient to declare vars here
                string s1= '';
                // vars for lease extension premium calc 
        
                // MAIN SECTION
                for(Offer__c rec : Ids)
                {       
                    // update Offer NAME 
                    rec.Name= '(' + string.valueOf(rec.Offer_date__c) + ') £'+rec.Offer_amount__c.format() + ' <-> ' 
                                + '£'+rec.Counter_Offer__c.format() + ' (' + string.valueOf(rec.Counter_date__c) +')';

                }
                update Ids;
            }
        }  
    }